name: build_ucmi_system_github_release
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "待操作的系统包下载地址"
        required: true
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          echo "date=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f4)" >> $GITHUB_ENV
          if [[ "$(cat /etc/issue | grep 22.04)" == "" ]]; then
              echo "device=cmi" >> $GITHUB_ENV
              echo "ORIGN_ZIP_NAME=miui_CMI_V13.0.5.0.SJACNXM_79609f2b93_12.0.zip" >> $GITHUB_ENV
          else
              echo "device=umi" >> $GITHUB_ENV
              echo "ORIGN_ZIP_NAME=miui_UMI_V13.0.7.0.SJBCNXM_1beabe6d7f_12.0.zip" >> $GITHUB_ENV
          fi
          sudo apt install python3 python3-pip aria2 zip p7zip-full tar zipalign zstd
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          pip3 install pycryptodome
          pip3 install setuptools
          pip3 install docopt
          pip3 install requests
          pip3 install beautifulsoup4
          pip3 install --ignore-installed pyyaml
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
      - name: 2.下载系统包
        run: |
          aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" ${{ github.event.inputs.URL }}
          if [[ "${{ env.device }}" == "umi" ]]; then
              aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" https://hugeota.d.miui.com/V13.0.7.0.SJBCNXM/miui_UMI_V13.0.7.0.SJBCNXM_1beabe6d7f_12.0.zip
          else
              aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -d "$GITHUB_WORKSPACE" https://hugeota.d.miui.com/V13.0.5.0.SJACNXM/miui_CMI_V13.0.5.0.SJACNXM_79609f2b93_12.0.zip
          fi
      - name: 3.解包
        run: |
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/payload-dumper-go
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
          mkdir -p "$GITHUB_WORKSPACE"/THYMEPRE
          mkdir -p "$GITHUB_WORKSPACE"/${{ env.device }}
          mkdir -p "$GITHUB_WORKSPACE"/images
          mkdir -p "$GITHUB_WORKSPACE"/simages
          mkdir -p "$GITHUB_WORKSPACE"/zip
          mkdir -p "$GITHUB_WORKSPACE"/firmware
          ZIP_NAME_THYMEPRE=$(echo ${{ github.event.inputs.URL }} | cut -d"/" -f5)
          7z x "$GITHUB_WORKSPACE"/$ZIP_NAME_THYMEPRE -r -o"$GITHUB_WORKSPACE"/THYMEPRE
          rm -rf "$GITHUB_WORKSPACE"/$ZIP_NAME_THYMEPRE
          7z x "$GITHUB_WORKSPACE"/${{ env.ORIGN_ZIP_NAME }} -r -o"$GITHUB_WORKSPACE"/${{ env.device }} firmware-update
          for i in odm vendor; do
              7z x "$GITHUB_WORKSPACE"/${{ env.ORIGN_ZIP_NAME }} -o"$GITHUB_WORKSPACE"/${{ env.device }} $i.transfer.list
              7z x "$GITHUB_WORKSPACE"/${{ env.ORIGN_ZIP_NAME }} -o"$GITHUB_WORKSPACE"/${{ env.device }} $i.patch.dat
              7z x "$GITHUB_WORKSPACE"/${{ env.ORIGN_ZIP_NAME }} -o"$GITHUB_WORKSPACE"/${{ env.device }} $i.new.dat.br
              "$GITHUB_WORKSPACE"/tools/brotli -d "$GITHUB_WORKSPACE"/${{ env.device }}/$i.new.dat.br
              rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/$i.new.dat.br
              python3 "$GITHUB_WORKSPACE"/tools/sdat2img.py "$GITHUB_WORKSPACE"/${{ env.device }}/$i.transfer.list "$GITHUB_WORKSPACE"/${{ env.device }}/$i.new.dat "$GITHUB_WORKSPACE"/${{ env.device }}/$i.img
              rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/$i.patch.dat
              rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/$i.transfer.list
              rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/$i.new.dat
          done
          sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/${{ env.device }}/vendor.img "$GITHUB_WORKSPACE"/${{ env.device }}
          rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/vendor.img
          for i in system product system_ext; do
              "$GITHUB_WORKSPACE"/tools/payload-dumper-go -p $i "$GITHUB_WORKSPACE"/THYMEPRE/payload.bin
              mv "$GITHUB_WORKSPACE"/payload/$i.img "$GITHUB_WORKSPACE"/images/$i.img
              sudo python3 "$GITHUB_WORKSPACE"/tools/imgextractorLinux.py "$GITHUB_WORKSPACE"/images/$i.img "$GITHUB_WORKSPACE"/images
              rm -rf "$GITHUB_WORKSPACE"/images/$i.img
          done
          "$GITHUB_WORKSPACE"/tools/payload-dumper-go -p modem "$GITHUB_WORKSPACE"/THYMEPRE/payload.bin
          mv "$GITHUB_WORKSPACE"/payload/modem.img "$GITHUB_WORKSPACE"/images/modem.img
          rm -rf "$GITHUB_WORKSPACE"/payload
          rm -rf "$GITHUB_WORKSPACE"/THYMEPRE
          rm -rf "$GITHUB_WORKSPACE"/${{ env.ORIGN_ZIP_NAME }}
      - name: 4.替换相关文件
        run: |
          sudo rm -rf "$GITHUB_WORKSPACE"/images/product/etc/device_features/*
          sudo rm -rf "$GITHUB_WORKSPACE"/images/product/overlay/DeviceAndroidConfig.apk
          sudo rm -rf "$GITHUB_WORKSPACE"/images/product/overlay/DeviceConfig.apk
          sudo cp -f "$GITHUB_WORKSPACE"/${{ env.device }}_files/AospFrameworkResOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay
          sudo cp -f "$GITHUB_WORKSPACE"/${{ env.device }}_files/DevicesAndroidOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay
          sudo cp -f "$GITHUB_WORKSPACE"/${{ env.device }}_files/DevicesOverlay.apk "$GITHUB_WORKSPACE"/images/product/overlay
          sudo cp -f "$GITHUB_WORKSPACE"/${{ env.device }}_files/${{ env.device }}.xml "$GITHUB_WORKSPACE"/images/product/etc/device_features
          sudo unzip -o "$GITHUB_WORKSPACE"/${{ env.device }}_files/nfc.zip -d "$GITHUB_WORKSPACE"/images/system_ext
          sudo rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/vendor/recovery-from-boot.p
          sudo rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}/vendor/bin/install-recovery.sh
          sudo mv -f "$GITHUB_WORKSPACE"/${{ env.device }}_files/vbmeta.img "$GITHUB_WORKSPACE"/${{ env.device }}/firmware-update
          sudo mv -f "$GITHUB_WORKSPACE"/${{ env.device }}_files/vbmeta_system.img "$GITHUB_WORKSPACE"/${{ env.device }}/firmware-update
          sudo unzip -o "$GITHUB_WORKSPACE"/tools/flashtools.zip -d "$GITHUB_WORKSPACE"/images
          sudo cp -r "$GITHUB_WORKSPACE"/${{ env.device }}/firmware-update "$GITHUB_WORKSPACE"/images
          sudo mv -f "$GITHUB_WORKSPACE"/tools/super_empty.img "$GITHUB_WORKSPACE"/images/firmware-update
          sudo tar -zxvf "$GITHUB_WORKSPACE"/${{ env.device }}_files/boot_official.tar.gz -C "$GITHUB_WORKSPACE"/images
          sudo tar -zxvf "$GITHUB_WORKSPACE"/${{ env.device }}_files/boot_magisk.tar.gz -C "$GITHUB_WORKSPACE"/images
          sudo cp -r "$GITHUB_WORKSPACE"/${{ env.device }}/* "$GITHUB_WORKSPACE"/images
          sudo rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}
          # 删除预装 By PedroZ
          sudo rm -rf "$GITHUB_WORKSPACE"/images/system/system/app/MSA
          for files in MIShop MIUINewHome MIUIGameCenter MIUIHuanji MIUIYoupin MIUIDuokanReader MIUIEmail MIUIVipAccount SmartHome MIMediaEditor MIGalleryLockscreen Health; do
              dataapp=$(find "$GITHUB_WORKSPACE"/images/system/system/data-app/ -name $files)
              sudo rm -rf $dataapp
          done
          for files in MIUIMusic; do
              prepkg=$(find "$GITHUB_WORKSPACE"/images/system/system/priv-app/ -name $files)
              sudo rm -rf $prepkg
          done
          # 修改props By PedroZ
          if [[ "${{ env.device }}" == "umi" ]]; then
              sudo sed -i 's/ro.product.mod_device=[^*]*/ro.product.mod_device=umi_pre/' "$GITHUB_WORKSPACE"/images/system/system/build.prop
              sudo sed -i 's/ro.miui.cust_device=[^*]*/ro.miui.cust_device=umi/' "$GITHUB_WORKSPACE"/images/system/system/build.prop
          else
              sudo sed -i 's/ro.product.mod_device=[^*]*/ro.product.mod_device=cmi_pre/' "$GITHUB_WORKSPACE"/images/system/system/build.prop
              sudo sed -i 's/ro.miui.cust_device=[^*]*/ro.miui.cust_device=cmi/' "$GITHUB_WORKSPACE"/images/system/system/build.prop
          fi
          # 声音动效动画 By PedroZ
          sudo unzip -o -q "$GITHUB_WORKSPACE"/tools/etc.zip -d "$GITHUB_WORKSPACE"/images/system/system/etc/audio/
          rm -rf "$GITHUB_WORKSPACE"/${{ env.device }}_files
          # 基带更新 By Meetingfate
          mkdir -p "$GITHUB_WORKSPACE"/modem "$GITHUB_WORKSPACE"/modem1
          sudo mount -v -t vfat ""$GITHUB_WORKSPACE"/images/modem.img" ""$GITHUB_WORKSPACE"/modem/"
          sudo mount -v -t vfat ""$GITHUB_WORKSPACE"/images/firmware-update/NON-HLOS.bin" ""$GITHUB_WORKSPACE"/modem1/"
          for i in $(ls "$GITHUB_WORKSPACE"/modem/image/); do
              if [[ $i != modem_pr ]] && [[ $i != sdx55 ]] && [[ $i != sdx55m ]]; then
                  sudo rm -rf "$GITHUB_WORKSPACE"/modem/image/$i
              fi
          done
          for i in $(sudo ls "$GITHUB_WORKSPACE"/modem1/image/); do
              if [[ $i = modem_pr ]] || [[ $i = sdx55 ]] || [[ $i = sdx55m ]]; then
                  sudo rm -rf "$GITHUB_WORKSPACE"/modem1/image/$i
              fi
          done
          sudo mv "$GITHUB_WORKSPACE"/modem1/image/* "$GITHUB_WORKSPACE"/modem/image/
          sudo umount -v "$GITHUB_WORKSPACE"/modem/
          sudo umount -v "$GITHUB_WORKSPACE"/modem1/
          sudo mv -f "$GITHUB_WORKSPACE"/images/modem.img "$GITHUB_WORKSPACE"/images/firmware-update/NON-HLOS.bin
          sudo rm -rf "$GITHUB_WORKSPACE"/modem
          sudo rm -rf "$GITHUB_WORKSPACE"/modem1
      - name: 5.打包
        run: |
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/mke2fs
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/e2fsdroid
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/img2simg
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/brotli
          sudo chmod 777 "$GITHUB_WORKSPACE"/tools/lpmake
          product_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/product | awk {'print $1'})
          product_size=$(echo "$product_size + 20971520" | bc)
          product_size=$(echo "$product_size / 4096" | bc)
          vendor_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/vendor | awk {'print $1'})
          vendor_size=$(echo "$vendor_size + 9895936" | bc)
          vendor_size=$(echo "$vendor_size / 4096" | bc)
          system_ext_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/system_ext | awk {'print $1'})
          system_ext_size=$(echo "$system_ext_size + 23488103" | bc)
          system_ext_size=$(echo "$system_ext_size / 4096" | bc)
          system_size=$(sudo du -sb "$GITHUB_WORKSPACE"/images/system | awk {'print $1'})
          system_size=$(echo "$system_size + 104857600" | bc)
          system_size=$(echo "$system_size / 4096" | bc)
          for i in product vendor system_ext system; do
              sudo python3 "$GITHUB_WORKSPACE"/tools/fspatch.py "$GITHUB_WORKSPACE"/images/$i "$GITHUB_WORKSPACE"/images/TI_config/"$i"_fs_config
              "$GITHUB_WORKSPACE"/tools/mke2fs -O ^has_journal -L $i -I 256 -M /$i -m 0 -t ext4 -b 4096 "$GITHUB_WORKSPACE"/images/$i.img $(eval echo "$"$i"_size")
              sudo "$GITHUB_WORKSPACE"/tools/e2fsdroid -e -T 1230768000 -C "$GITHUB_WORKSPACE"/images/TI_config/"$i"_fs_config -S "$GITHUB_WORKSPACE"/images/TI_config/"$i"_file_contexts -f "$GITHUB_WORKSPACE"/images/$i -a /$i "$GITHUB_WORKSPACE"/images/$i.img
              resize2fs -f -M "$GITHUB_WORKSPACE"/images/$i.img
              eval "$i"_size=$(du -sb "$GITHUB_WORKSPACE"/images/$i.img | awk {'print $1'})
              sudo rm -rf "$GITHUB_WORKSPACE"/images/$i
          done
          sudo rm -rf "$GITHUB_WORKSPACE"/images/TI_config
          "$GITHUB_WORKSPACE"/tools/lpmake --metadata-size 65536 --super-name super --block-size 4096 --partition odm:readonly:134217728:qti_dynamic_partitions --image odm="$GITHUB_WORKSPACE"/images/odm.img --partition product:readonly:$product_size:qti_dynamic_partitions --image product="$GITHUB_WORKSPACE"/images/product.img --partition system:readonly:$system_size:qti_dynamic_partitions --image system="$GITHUB_WORKSPACE"/images/system.img --partition system_ext:readonly:$system_ext_size:qti_dynamic_partitions --image system_ext="$GITHUB_WORKSPACE"/images/system_ext.img --partition vendor:readonly:$vendor_size:qti_dynamic_partitions --image vendor="$GITHUB_WORKSPACE"/images/vendor.img --device super:9126805504 --metadata-slots 2 --group qti_dynamic_partitions:9126805504 -F --output "$GITHUB_WORKSPACE"/images/super.img
          for i in product system system_ext vendor odm; do
              rm -rf "$GITHUB_WORKSPACE"/images/$i.img
          done
          zstd "$GITHUB_WORKSPACE"/images/super.img -o "$GITHUB_WORKSPACE"/images/super.zst --rm
          if [[ "${{ env.device }}" == "umi" ]]; then
              sudo 7z a "$GITHUB_WORKSPACE"/zip/miui_UMIPRE_${{ env.date }}.zip "$GITHUB_WORKSPACE"/images/*
              sudo rm -rf "$GITHUB_WORKSPACE"/images
              md5=$(md5sum "$GITHUB_WORKSPACE"/zip/miui_UMIPRE_${{ env.date }}.zip)
              zipmd5=${md5:0:10}
              mv "$GITHUB_WORKSPACE"/zip/miui_UMIPRE_${{ env.date }}.zip "$GITHUB_WORKSPACE"/zip/miui_UMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip
              cd "$GITHUB_WORKSPACE"/zip
              sudo split -b 1536M -d "$GITHUB_WORKSPACE"/zip/miui_UMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip miui_UMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip
              sudo rm -rf "$GITHUB_WORKSPACE"/zip/miui_UMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip
              cd "$GITHUB_WORKSPACE"
              touch file.log
              echo "miui_UMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip" > file.log
          else
              sudo 7z a "$GITHUB_WORKSPACE"/zip/miui_CMIPRE_${{ env.date }}.zip "$GITHUB_WORKSPACE"/images/*
              sudo rm -rf "$GITHUB_WORKSPACE"/images
              md5=$(md5sum "$GITHUB_WORKSPACE"/zip/miui_CMIPRE_${{ env.date }}.zip)
              zipmd5=${md5:0:10}
              mv "$GITHUB_WORKSPACE"/zip/miui_CMIPRE_${{ env.date }}.zip "$GITHUB_WORKSPACE"/zip/miui_CMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip
              cd "$GITHUB_WORKSPACE"/zip
              sudo split -b 1536M -d "$GITHUB_WORKSPACE"/zip/miui_CMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip miui_CMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip
              sudo rm -rf "$GITHUB_WORKSPACE"/zip/miui_CMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip
              cd "$GITHUB_WORKSPACE"
              touch file.log
              echo "miui_CMIPRE_"${{ env.date }}"_"$zipmd5"_12.0_2in1_Root.zip" > file.log
          fi
      - name: 6.上传到Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: ${{ github.workspace }}/zip/*
          name: "${{ env.date }}"
          tag: "${{ env.date }}"
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 7.删除工作流运行
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
